package bubblepop;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JOptionPane;


/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author LGY
 */
public class Main extends javax.swing.JFrame 	
{

    /**
     * Creates new form main
     */
	
	public static String level;	//하, 중, 상
    ItemSelect it_s;
	
    public Main() 
    {
        initComponents();
    }

    /**
a     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();


        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BubblePop");
        setResizable(false);

        jButton1.setText("다음");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("랭킹");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("난이도 선택");

        //jToggleButton1.setToolTipText("");
       
        jToggleButton1.setText("하");
        jToggleButton2.setText("중");
        jToggleButton3.setText("상");
        
        jToggleButton1.addItemListener(new ItemListener()
        {
        	public void itemStateChanged(ItemEvent ev) 
        	{
        		if(ev.getStateChange()==ItemEvent.SELECTED)
        		{
        			jToggleButton2.setSelected(false);
    		    	jToggleButton3.setSelected(false);
    		    	level="하";
    			}
        		else if(ev.getStateChange()==ItemEvent.DESELECTED)
        		{
        			level=null;
        		}
		   }
		});
        
        jToggleButton2.addItemListener(new ItemListener()
        {
        	public void itemStateChanged(ItemEvent ev) 
        	{
        		if(ev.getStateChange()==ItemEvent.SELECTED)
        		{
        			jToggleButton1.setSelected(false);
    		    	jToggleButton3.setSelected(false);
    		    	level="중";
    			}
        		else if(ev.getStateChange()==ItemEvent.DESELECTED)
        		{
        			level=null;
        		}
		   }
		});

        jToggleButton3.addItemListener(new ItemListener()
        {
        	public void itemStateChanged(ItemEvent ev) 
        	{
        		if(ev.getStateChange()==ItemEvent.SELECTED)
        		{
        			jToggleButton1.setSelected(false);
    		    	jToggleButton2.setSelected(false);
    		    	level="상";
    			}
        		else if(ev.getStateChange()==ItemEvent.DESELECTED)
        		{
        			level=null;
        		}
		   }
		});

/////////////////////////////////////////////////////////////////////////////////////////////////////        
///////////X눌렀을 때 종료할 거냐 묻는 코드///////////////////////////////////////////////////////////////////
    	this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
    	this.addWindowListener(new java.awt.event.WindowAdapter() 
    	{
	        @Override
	        public void windowClosing(java.awt.event.WindowEvent e) 
	        {
	        	 if (JOptionPane.showConfirmDialog(null, 
	        	            "정말 게임을 종료하시겠습니까?", "Really Closing?", 
	        	            JOptionPane.YES_NO_OPTION,
	        	            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
	        	            System.exit(0);
	        	        }
	        }
	    });
///////////////////////////////////////////////////////////////////////////////////////////////////////

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                                                        

    //다음 버튼을 눌렀을 때
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {   
    	
    	
    	if(level==null)	//난이도가 선택되지 않은 경우
    	{
    		
    		JOptionPane.showMessageDialog(this, "난이도를 먼저 선택해 주세요.", null, JOptionPane.WARNING_MESSAGE);
    	}
    	else	//난이도 선택 시
    	{
			String content = "선택하신 난이도는 \'" + level + "\' 입니다.";
		    
			int reply=JOptionPane.showConfirmDialog(this, content, "레벨 선택 확인", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
			
			if (reply == JOptionPane.YES_OPTION)
			{
				//난이도 선택화면을 띄운다
				//it_s.main();
		
				Game_Info game_info=new Game_Info(level);
				
				ItemSelect frame = new ItemSelect(game_info, this);
				frame.setResizable(false);
				frame.setVisible(true);
		    }
			else
			{
				//다시 메인
		    }
    	}
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
    {                                         
        //랭킹 버튼을 눌렀을 때
    	Ranking frame = new Ranking();
    	frame.setResizable(false);
    	frame.setVisible(true);
    	dispose();
    }                      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration     
    
}
